% Before running this code, please first open CERR and load within CERR the file
% "TestProstate_downsampled128by128.mat"


global planC; % all plan info are saved in planC by CERR as a global variable;

[oar,num_oar] = ExtractingInfluenceMatrix(1:54); % generating dose influence matrix; 
%Note that 54 here can be changed into any number given it is greater than the total number of OARs

save oar8Beams2 oar num_oar;

TPP1_prostate;
TPP2_prostate;

% the final beamlet intensity is saved in the array: "WV";

plotdifferent3(WV,planC,'8 Beam'); % Generate the dose distribution using CERR and name the corresponding dose distribution as "8 Beam".
% WV here is the beamlet intensity generated by the TPP approach.
